spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Abc123+++
    databaseName: cloud_test

app:
  export:
    path: src/main/resources/output
    filename: database_structure.docx